-- MySQL Script generated by MySQL Workbench
-- Tue May 28 18:55:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vanguard
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Vanguard` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Vanguard` ;

-- -----------------------------------------------------
-- Table `Vanguard`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`estado` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`estado_id`),
  UNIQUE INDEX `nome_estado_UNIQUE` (`nome_estado` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`Cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`Cidades` (
  `cidade_id` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(100) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`cidade_id`, `estado_id`),
  INDEX `fk_estado_idx` (`estado_id` ASC),
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `Vanguard`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `cep` INT(8) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `num_predial` INT(5) NOT NULL,
  `cidades_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `is_admin` TINYINT(1) DEFAULT 0,  -- Campo para indicar se o usuário é administrador (0 = Não, 1 = Sim)
  PRIMARY KEY (`usuario_id`, `cidades_id`, `estado_id`),
  UNIQUE INDEX `cep_UNIQUE` (`cep` ASC),
  INDEX `fk_Usuario_cidades1_idx` (`cidades_id` ASC, `estado_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_Usuario_cidades1`
    FOREIGN KEY (`cidades_id`, `estado_id`)
    REFERENCES `Vanguard`.`Cidades` (`cidade_id`, `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `classe` VARCHAR(150) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (`id`),
      ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`carrinho` (
  `carrinho_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`carrinho_id`, `usuario_id`),
  INDEX `fk_carrinho_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_carrinho_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Vanguard`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`Produto_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`Produto_carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `carrinho_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Produto_id`, `carrinho_id`),
  INDEX `fk_Produto_carrinho_Produto1_idx` (`Produto_id` ASC),
  INDEX `fk_Produto_carrinho_carrinho1_idx` (`carrinho_id` ASC),
  CONSTRAINT `fk_Produto_carrinho_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `Vanguard`.`Produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_carrinho_carrinho1`
    FOREIGN KEY (`carrinho_id`)
    REFERENCES `Vanguard`.`carrinho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
