-- MySQL Script generated by MySQL Workbench
-- Thu Sep 12 10:13:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vanguard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vanguard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vanguard` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Vanguard` ;

-- -----------------------------------------------------
-- Table `Vanguard`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`estado` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`cidades` (
  `cidade_id` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(100) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`cidade_id`, `estado_id`),
  INDEX `fk_Cidades_Estado_idx` (`estado_id` ASC),
  CONSTRAINT `fk_Cidades_Estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `Vanguard`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `foto` LONGBLOB NULL,
  `estado_id` INT NOT NULL,
  `cidades_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `estado_id`, `cidades_id`),
  INDEX `fk_Usuario_Cidades1_idx` (`cidades_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_usuario_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_Usuario_Cidades1`
    FOREIGN KEY (`cidades_id`)
    REFERENCES `Vanguard`.`cidades` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `Vanguard`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_carrinho_Usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_carrinho_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Vanguard`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -- -----------------------------------------------------
-- Table `Vanguard`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`funcionario` (
  `nome` VARCHAR(255) NOT NULL,
  `usuario_id` INT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `usuario_estado_id` INT NOT NULL,
  `usuario_cidades_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_estado_id` ASC, `usuario_cidades_id` ASC),
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_estado_id` , `usuario_cidades_id`)
    REFERENCES `Vanguard`.`usuario` (`estado_id` , `cidades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`relatorio` (
  `relatorio_id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `funcionario_usuario_id` INT NOT NULL,
  `funcionario_usuario_cidades_id` INT NULL,
  `funcionario_usuario_cidades_estado_id` INT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`relatorio_id`, `funcionario_usuario_id`, `funcionario_usuario_cidades_id`, `funcionario_usuario_cidades_estado_id`),
  INDEX `fk_relatorio_funcionario1_idx` (`funcionario_usuario_id` ASC, `funcionario_usuario_cidades_id` ASC, `funcionario_usuario_cidades_estado_id` ASC),
  CONSTRAINT `fk_relatorio_funcionario1`
    FOREIGN KEY (`funcionario_usuario_id`)
    REFERENCES `Vanguard`.`funcionario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`servico` (
  `tipo` VARCHAR(10) NOT NULL,
  `comentario` TEXT NOT NULL,
  `servico_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`servico_id`, `usuario_id`),
  INDEX `fk_solicitacao_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_solicitacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Vanguard`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`Avaliacao` (
  `avaliacao_id` INT NOT NULL,
  `pontos` INT(5) NULL,
  `texto` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`avaliacao_id`, `usuario_id`),
  INDEX `fk_Avaliacao_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Avaliacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Vanguard`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
